/*==============================================================================
    Project: TEJ2O Activity1 - Output
    Version: 3.0                Date: October 22, 2018
    Target: UBMP3.0             Processor: PIC16F1459

    A simple output timing program demonstrating port output to the UBMP LEDs.
==============================================================================*/

#include    "xc.h"              // XC general include file

#include    "stdint.h"          // Include integer definitions
#include    "stdbool.h"         // Include Boolean (true/false) definitions

#include    "UBMP3.h"           // Include UBMP3 constant symbol definitions

// TODO Set linker ROM ranges to 'default,-0-C03' under "Memory model" pull-down.
// TODO Set linker Code offset to '0xC04' under "Additional options" pull-down.

/*==============================================================================
    Main function and loop. The compiler looks for main() to start the program.
==============================================================================*/

int main(void)                  // Main function runs every startup
{
    initOsc();                  // Initialize oscillator
    initPorts();                // Initialize I/O pins and peripherals
//  initANC();                  // Optional - Initialize PORTC analogue inputs
	
	
    while(1)                    // Repeat this loop of code continuously
	{
        LED3 = 1;               // Turn 4 main UBMP LEDs on in sequence
        __delay_ms(100);
        LED4 = 1;
        __delay_ms(100);
        LED5 = 1;
        __delay_ms(100);
        LED6 = 1;
        __delay_ms(100);
        
        LED3 = 0;               // Turn LEDs off in sequence
        __delay_ms(100);
        LED4 = 0;
        __delay_ms(100);
        LED5 = 0;
        __delay_ms(100);
        LED6 = 0;
        __delay_ms(100);
        
        if(S1 == 0)             // Enter the bootloader if S1 is pressed.
        {
            asm("movlp 0x00");
            asm("goto 0x001C");
        }		
    }
}

/* Program Analysis
 * 
 * 1.   Think about the first line of code in the main while loop: 
 *          LED3 = 1;
 *      How does MPLAB know which port pin corresponds to each LED?
 * 
 * 2.   The __delay_ms() function delays for a specified number of milliseconds.
 *      What value would you use in the __delay_ms() function to delay for 1s?
 *      Try it. Change the value inside the brackets, re-build the program, and
 *      download it into your circuit board.
 * 
 * 3.   A microsecond time delay function, __delay_us(), is also available.
 *      Change the delays in the program to 100us. Can you still see the LEDs
 *      cycling on and off with this new delay?
 *  
 * 4.   There is a maximum time delay that can be generated by __delay_ms(). 
 *      How would you find it? Try different values of time delays and rebuild
 *      our project to see if a build error occurs. (Hint: think of a good way
 *      to try to guess an unknown number.)
 * 
 * Programming Activities
 * 
 * 1.   Use time delays and LED commands to make your own unique LED flashing
 *      pattern.
 * 
 * 2.   Instead of controlled each LED individually, a latch command can be used
 *      to control all port outputs at the same time. For example,
 * 
 *          LATC = 0b11110000;
 * 
 *      turns on all 4 LEDs, and 
 * 
 *          LATC = 0b10010000;
 * 
 *      turns on only 2 LEDs. Comment out your previous flashing pattern using
 *      LED numbers, and reproduce your flashing pattern using latch commands
 *      and time delays.
 */
